#:schema node_modules/wrangler/config-schema.json

name = "subfeed"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "subfeed.jcmonteiro.dev"
zone_name = "jcmonteiro.dev"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "subfeed-db"
database_id = "8ba63947-17b9-4d85-8da1-36a08f18c3ad"
